version: "2"

services:
  transmission:
    image: haugene/transmission-openvpn
    container_name: transmission-openvpn
    privileged: true
    restart: always
    ports:
      - "9091:9091"
    networks:
      - plexnet
    dns:
      - 8.8.8.8
      - 8.8.4.4
    cap_add:
      - NET_ADMIN
    environment:
      - OPENVPN_PROVIDER=${VPN_PROVIDER}
      - OPENVPN_CONFIG=${VPN_CONFIG}
      - OPENVPN_USERNAME=${VPN_USERNAME}
      - OPENVPN_PASSWORD=${VPN_PASSWORD}
      - OPENVPN_OPTS=--inactive 3600 --ping 10 --ping-exit 60
      - LOCAL_NETWORK=${LOCAL_NET}
      - TRANSMISSION_SPEED_LIMIT_UP=${TRANSMISSION_UP}
      - TRANSMISSION_SPEED_LIMIT_UP_ENABLED=true
      - TRANSMISSION_SPEED_LIMIT_DOWN=${TRANSMISSION_DOWN}
      - TRANSMISSION_SPEED_LIMIT_DOWN_ENABLED=true
      - TRANSMISSION_SCRIPT_TORRENT_DONE_ENABLED=true
      - TRANSMISSION_SCRIPT_TORRENT_DONE_FILENAME=/bin/unrar_torrent.sh
      - TRANSMISSION_DOWNLOAD_QUEUE_ENABLED=true
      - TRANSMISSION_DOWNLOAD_QUEUE_SIZE=15
    volumes:
      - ${CONFIG_DIR}/transmission:/data/transmission-home
      - ${DOWNLOAD_DIR}/Videos/TV:/data/completed/tv
      - ${DOWNLOAD_DIR}/Videos/Movies:/data/completed/movies
      - ${DOWNLOAD_DIR}/transmission/completed:/data/completed
      - ${DOWNLOAD_DIR}/transmission/incomplete:/data/incomplete
      - ${PWD}/unrar_torrent.sh:/bin/unrar_torrent.sh
      - /etc/localtime:/etc/localtime:ro
    devices:
      - /dev/net/tun 

  radarr:
    image: linuxserver/radarr
    container_name: radarr
    restart: always
    ports:
      - "7878:7878"
    networks:
      - plexnet
    environment:
      - PUID=911
      - PGID=911
      - TZ=America/Chicago
    volumes:
      - ${CONFIG_DIR}/radarr:/config
      - ${DOWNLOAD_DIR}/Videos/Movies:/data/completed/movies/
      - ${MEDIA_DIR}/Videos/Movies:/movies
      - /etc/localtime:/etc/localtime:ro
  
  sonarr:
    image: linuxserver/sonarr
    container_name: sonarr
    restart: always
    ports:
      - "8989:8989"
    networks:
      - plexnet
    environment:
      - PUID=911
      - PGID=911
      - TZ=America/Chicago
    volumes:
      - ${CONFIG_DIR}/sonarr:/config
      - ${DOWNLOAD_DIR}/Videos/TV:/data/completed/tv/
      - ${MEDIA_DIR}/Videos/TV:/tv
      - /etc/localtime:/etc/localtime:ro
      
  jackett:
    image: linuxserver/jackett
    container_name: jackett
    restart: always
    ports:
      - "9117:9117"
    networks:
      - plexnet
    environment:
      - PUID=911
      - PGID=911
      - TZ=America/Chicago
    volumes:
      - ${CONFIG_DIR}/jackett/config:/config
      - ${CONFIG_DIR}/jackett/downloads:/downloads
      - /etc/localtime:/etc/localtime:ro

  plex:
    image: plexinc/pms-docker:plexpass
    container_name: plex
    restart: always
    ports:
      - "32400:32400"
      - "1900:1900"
      - "3005:3005"
      - "5353:5353"
      - "8324:8324"
      - "32410:32410"
      - "32412:32412"
      - "32413:32413"
      - "32414:32414"
      - "32469:32469"
    networks:
      - plexnet
    environment:
      - PLEX_UID=911
      - PLEX_GID=911
      - TZ=America/Chicago
      - ADVERTISE_IP=http://${IP}:32400/
      - PLEX_CLAIM=${CLAIM_CODE}
    hostname: ${NAME}
    volumes:
      - ${CONFIG_DIR}/plex:/config
      - ${MEDIA_DIR}:/data
      - /etc/localtime:/etc/localtime:ro

  plexpy:
    image: linuxserver/plexpy
    container_name: plexpy
    restart: always
    ports:
      - "8181:8181"
    environment:
      - PLEX_UID=911
      - PLEX_GID=911
      - TZ=America/Chicago
    volumes: 
      - ${CONFIG_DIR}/plexpy:/config 
      - ${CONFIG_DIR}/plex/Library/Application\ Support/Plex\ Media\ Server/Logs:/logs:ro 
      - /etc/localtime:/etc/localtime:ro

networks:
  plexnet:
    driver: bridge

