version: "2.4"

services:
  deluge:
    image: binhex/arch-delugevpn
    container_name: delugevpn
    restart: always
    ports:
      - "8112:8112"
      - "8118:8118"
      - "58846:58846"
      - "58946:58946"
    dns:
      - 8.8.8.8
      - 8.8.4.4
      - 209.222.18.222
      - 209.222.18.218
      - 37.235.1.174
      - 1.1.1.1
      - 37.235.1.177
      - 1.0.0.1
    networks:
      - plexnet
    cap_add:
      - NET_ADMIN
    environment:
      - PUID=911
      - PGID=911
      - VPN_ENABLED=yes
      - VPN_USER=${VPN_USERNAME}
      - VPN_PASS=${VPN_PASSWORD}
      - VPN_PROV=pia
      - STRICT_PORT_FORWARD=yes
      - ENABLE_PRIVOXY=no
      - LAN_NETWORK=192.168.1.0/24
      - DELUGE_DAEMON_LOG_LEVEL=info
      - DELUGE_WEB_LOG_LEVEL=info
      - NAME_SERVERS=209.222.18.222,37.235.1.174,1.1.1.1,8.8.8.8,209.222.18.218,37.235.1.177,1.0.0.1,8.8.4.4
      - DEBUG=true
      - UMASK=000
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - ${CONFIG_DIR}/deluge:/config
      - ${DOWNLOAD_DIR}/Videos/TV:/data/completed/tv
      - ${DOWNLOAD_DIR}/Videos/Movies:/data/completed/movies
      - ${DOWNLOAD_DIR}/deluge/completed:/data/completed
      - ${DOWNLOAD_DIR}/deluge/incomplete:/data/incomplete
      - ${CONFIG_DIR}/torrents:/data/torrents

  radarr:
    image: linuxserver/radarr:latest
    container_name: radarr
    restart: always
    ports:
      - "7878:7878"
    networks:
      - plexnet
    environment:
      - PUID=911
      - PGID=911
      - TZ=America/Chicago
    volumes:
      - ${CONFIG_DIR}/radarr:/config
      - ${DOWNLOAD_DIR}/Videos/Movies:/data/completed/movies/
      - ${MEDIA_DIR}/Videos/Movies:/movies
      - /etc/localtime:/etc/localtime:ro
      - ${TEMP_DIR}/radarr:/tmp
  
  sonarr:
    image: linuxserver/sonarr
    container_name: sonarr
    restart: always
    ports:
      - "8989:8989"
    networks:
      - plexnet
    environment:
      - PUID=911
      - PGID=911
      - TZ=America/Chicago
    volumes:
      - ${CONFIG_DIR}/sonarr:/config
      - ${DOWNLOAD_DIR}/Videos/TV:/data/completed/tv/
      - ${MEDIA_DIR}/Videos/TV:/tv
      - /etc/localtime:/etc/localtime:ro
      - ${TEMP_DIR}/sonarr:/tmp

  bazarr:
    image: linuxserver/bazarr
    container_name: bazarr
    restart: always
    ports:
      - "6767:6767"
    networks:
      - plexnet
    environment:
      - PUID=911
      - PGID=911
      - TZ=America/Chicago
    volumes:
      - ${CONFIG_DIR}/bazarr:/config
      - ${MEDIA_DIR}/Videos/Movies:/movies
      - ${MEDIA_DIR}/Videos/TV:/tv
      - /etc/localtime:/etc/localtime:ro
      - ${TEMP_DIR}/bazarr:/tmp

  jackett:
    image: linuxserver/jackett
    container_name: jackett
    restart: always
    ports:
      - "9117:9117"
    networks:
      - plexnet
    environment:
      - PUID=911
      - PGID=911
      - TZ=America/Chicago
    volumes:
      - ${CONFIG_DIR}/jackett/config:/config
      - ${CONFIG_DIR}/jackett/downloads:/downloads
      - /etc/localtime:/etc/localtime:ro
      - ${TEMP_DIR}/jackett:/tmp

  plex:
    image: plexinc/pms-docker:plexpass
    container_name: plex
    restart: always
    ports:
      - "32400:32400"
      - "1900:1900"
      - "3005:3005"
      - "5353:5353"
      - "8324:8324"
      - "32410:32410"
      - "32412:32412"
      - "32413:32413"
      - "32414:32414"
      - "32469:32469"
    networks:
      - plexnet
    environment:
      - PLEX_UID=911
      - PLEX_GID=911
      - TZ=America/Chicago
      - ADVERTISE_IP=http://192.168.1.15:32400/
      - PLEX_CLAIM=${CLAIM_CODE}
    hostname: Gilliam
    volumes:
      - ${CONFIG_DIR}/plex:/config
      - ${MEDIA_DIR}:/data
      - /etc/localtime:/etc/localtime:ro
      - ${TEMP_DIR}/plex:/tmp
    devices:
      - /dev/dri:/dev/dri
  tautulli:
    image: linuxserver/tautulli
    container_name: tautulli
    restart: always
    ports:
      - "8181:8181"
    environment:
      - PUID=911
      - PGID=911
      - TZ=America/Chicago
    volumes: 
      - ${CONFIG_DIR}/plexpy:/config 
      - /etc/localtime:/etc/localtime:ro
      - ${TEMP_DIR}/tautulli:/tmp
networks:
  plexnet:
    driver: bridge
